##  Numpy Overview

#### Set1

This lab will help us understand how regular Python arrays perform compared to NumPy arrays. Use the 
`timeit` module to evaluate their performance difference. 

In [101]:
#Create a regular Python array of 1000 integers -

anArray = range(1000)

In [102]:
arrPow2 = [x**2 for x in anArray]

In [103]:
import timeit
print(timeit.timeit(setup ='myArray = range(1000)',stmt='[x**2 for x in myArray]', number =1000))



#%timeit  [x ** 2 for x in myArray]

0.22471910000058415


In [104]:
#import ms.version
#ms.version.addpkg('numpy',1,13,3)
print(timeit.timeit(setup='import numpy as np;otherArray = np.arange(1000)',stmt='[x**2 for x in otherArray]', number=1000))

0.15035270000043965


## Numpy Data Types and Arrays
#### Set2

In [157]:
import numpy as np
import csv

with open('AAPL-2017.csv',newline='') as f:
    reader = csv.DictReader(f)
    data2017 = np.empty((0,6))
    withDate2017 = np.empty((0,7))
    #print(np.shape(data2017))
    #print(np.ndim(data2017))
    for row in reader:
        oneRow = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
        data2017 = np.append(data2017,oneRow,axis=0)
        row2 = np.array([[row['Date'],row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
        withDate2017 = np.append(withDate2017,row2,axis=0)
        
    print(data2017)
    #print(withDate2017)

[['115.800003' '116.330002' '114.760002' '116.150002' '113.013916'
  '28781900']
 ['115.849998' '116.510002' '115.750000' '116.019997' '112.887413'
  '21118100']
 ['115.919998' '116.860001' '115.809998' '116.610001' '113.461502'
  '22193600']
 ...
 ['170.100006' '170.779999' '169.710007' '170.600006' '168.663101'
  '21498200']
 ['171.000000' '171.850006' '170.479996' '171.080002' '169.137650'
  '16480200']
 ['170.520004' '170.589996' '169.220001' '169.229996' '167.308640'
  '25884400']]


In [108]:
a = np.array([1,2,3,4])
print (a.shape) # (4,)

(4,)


In [109]:
#So _caveat emptor_ - beware when you mix types when using arange()
a5 = np.arange(0.5, 5.8, 0.5, float)
print(a5)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [110]:
print(np.ceil((5.8-0.5)/.5))

11.0


In [111]:
a = np.array([1,2,3,4])
print (a.shape)

(4,)


In [112]:
a = np.array([[1,2,3,4]])  # Note extra pair of square-brackets
print (a.shape) # (1,4)
print(np.ndim(a))

(1, 4)
2


## Operations on Arrays

#### Set 3

In [113]:
with open('AAPL-2016.csv',newline='') as f:
    reader = csv.DictReader(f)
    data2016 = np.empty((0,6))
    withDate2016 = np.empty((0,7))
    #print(np.shape(data2016))
    #print(np.ndim(data2016))
    for row in reader:
        oneRow = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
        row2 = np.array([[row['Date'],row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
        data2016 = np.append(data2016,oneRow,axis=0)
        withDate2016 = np.append(withDate2016,row2,axis=0)
        
    #print(data2016)
    print(withDate2016)

[['2016-01-04' '102.610001' '105.370003' ... '105.349998' '100.274513'
  '67649400']
 ['2016-01-05' '105.750000' '105.849998' ... '102.709999' '97.761681'
  '55791000']
 ['2016-01-06' '100.559998' '102.370003' ... '100.699997' '95.848511'
  '68457400']
 ...
 ['2016-12-23' '115.589996' '116.519997' ... '116.519997' '113.373917'
  '14249500']
 ['2016-12-27' '116.519997' '117.800003' ... '117.260002' '114.093948'
  '18296900']
 ['2016-12-28' '117.519997' '118.019997' ... '116.760002' '113.607445'
  '20905900']]


In [114]:
#the size of both data sets
print(np.shape(data2016))
print(np.shape(data2017))

(250, 6)
(251, 6)


In [115]:
#I am not sure what this is or what it does
[(data2016[n], data2016[n -1 ] )for n in range(len(data2016)//2)]

[(array(['102.610001', '105.370003', '102.000000', '105.349998',
         '100.274513', '67649400'], dtype='<U32'),
  array(['117.519997', '118.019997', '116.199997', '116.760002',
         '113.607445', '20905900'], dtype='<U32')),
 (array(['105.750000', '105.849998', '102.410004', '102.709999',
         '97.761681', '55791000'], dtype='<U32'),
  array(['102.610001', '105.370003', '102.000000', '105.349998',
         '100.274513', '67649400'], dtype='<U32')),
 (array(['100.559998', '102.370003', '99.870003', '100.699997', '95.848511',
         '68457400'], dtype='<U32'),
  array(['105.750000', '105.849998', '102.410004', '102.709999',
         '97.761681', '55791000'], dtype='<U32')),
 (array(['98.680000', '100.129997', '96.430000', '96.449997', '91.803276',
         '81094400'], dtype='<U32'),
  array(['100.559998', '102.370003', '99.870003', '100.699997', '95.848511',
         '68457400'], dtype='<U32')),
 (array(['98.550003', '99.110001', '96.760002', '96.959999', '92.288696',
    

In [116]:
#Last 5 elements(row) in the table
print(data2016[-5:])

[['116.800003' '117.400002' '116.779999' '117.059998' '113.899338'
  '23783200']
 ['116.349998' '116.510002' '115.639999' '116.290001' '113.150139'
  '26085900']
 ['115.589996' '116.519997' '115.589996' '116.519997' '113.373917'
  '14249500']
 ['116.519997' '117.800003' '116.489998' '117.260002' '114.093948'
  '18296900']
 ['117.519997' '118.019997' '116.199997' '116.760002' '113.607445'
  '20905900']]


In [117]:
print(data2016[-5:])

[['116.800003' '117.400002' '116.779999' '117.059998' '113.899338'
  '23783200']
 ['116.349998' '116.510002' '115.639999' '116.290001' '113.150139'
  '26085900']
 ['115.589996' '116.519997' '115.589996' '116.519997' '113.373917'
  '14249500']
 ['116.519997' '117.800003' '116.489998' '117.260002' '114.093948'
  '18296900']
 ['117.519997' '118.019997' '116.199997' '116.760002' '113.607445'
  '20905900']]


In [118]:
#withDate2016
print(withDate2016[-5:])

[['2016-12-21' '116.800003' '117.400002' '116.779999' '117.059998'
  '113.899338' '23783200']
 ['2016-12-22' '116.349998' '116.510002' '115.639999' '116.290001'
  '113.150139' '26085900']
 ['2016-12-23' '115.589996' '116.519997' '115.589996' '116.519997'
  '113.373917' '14249500']
 ['2016-12-27' '116.519997' '117.800003' '116.489998' '117.260002'
  '114.093948' '18296900']
 ['2016-12-28' '117.519997' '118.019997' '116.199997' '116.760002'
  '113.607445' '20905900']]


In [155]:
print(withDate2017[:-1])

[['2017-01-03' '115.800003' '116.330002' ... '116.150002' '113.013916'
  '28781900']
 ['2017-01-04' '115.849998' '116.510002' ... '116.019997' '112.887413'
  '21118100']
 ['2017-01-05' '115.919998' '116.860001' ... '116.610001' '113.461502'
  '22193600']
 ...
 ['2017-12-26' '170.800003' '171.470001' ... '170.570007' '168.633423'
  '33185500']
 ['2017-12-27' '170.100006' '170.779999' ... '170.600006' '168.663101'
  '21498200']
 ['2017-12-28' '171.000000' '171.850006' ... '171.080002' '169.137650'
  '16480200']]


In [161]:
#trimming off the last row
newData2017 = withDate2017[:-1,2:]

#using delete
#careful to use it just once, it deletes from the array
#newData2017= np.delete(withDate2017,obj=251,axis=0)



#now print it
#print(np.shape(withDate2017))
print(np.shape(newData2017))

(250, 5)


##### NumPy lets you sum up the columns of an array
For example, to sum up `myArray`, you would say `myArray.sum(axis=0)`

Setting the axis to 0, tells it to iterate and sum down the rows. Setting the axis to 1 tells NumPy to sum across the columns.
. 

In [147]:
#Get the data to be analysed

Final2016 = data2016.astype(float)
Final2017= (data2017[:-1]).astype(float)


#printing
print(Final2016[-5:])
print(Final2017[-5:])

[[1.16800003e+02 1.17400002e+02 1.16779999e+02 1.17059998e+02
  1.13899338e+02 2.37832000e+07]
 [1.16349998e+02 1.16510002e+02 1.15639999e+02 1.16290001e+02
  1.13150139e+02 2.60859000e+07]
 [1.15589996e+02 1.16519997e+02 1.15589996e+02 1.16519997e+02
  1.13373917e+02 1.42495000e+07]
 [1.16519997e+02 1.17800003e+02 1.16489998e+02 1.17260002e+02
  1.14093948e+02 1.82969000e+07]
 [1.17519997e+02 1.18019997e+02 1.16199997e+02 1.16760002e+02
  1.13607445e+02 2.09059000e+07]]
[[1.74169998e+02 1.76020004e+02 1.74100006e+02 1.75009995e+02
  1.73023026e+02 2.09499000e+07]
 [1.74679993e+02 1.75419998e+02 1.74500000e+02 1.75009995e+02
  1.73023026e+02 1.61146000e+07]
 [1.70800003e+02 1.71470001e+02 1.69679993e+02 1.70570007e+02
  1.68633423e+02 3.31855000e+07]
 [1.70100006e+02 1.70779999e+02 1.69710007e+02 1.70600006e+02
  1.68663101e+02 2.14982000e+07]
 [1.71000000e+02 1.71850006e+02 1.70479996e+02 1.71080002e+02
  1.69137650e+02 1.64802000e+07]]


In [201]:
sum2016 = Final2016.sum(axis =0)
#print(sum2016)
volume2016a = (Final2016[-1]).sum(axis =0)
volume2016b = sum2016[-1]
print(volume2016a)
print(volume2016b)

20906482.107438
9634995700.0


In [202]:
sum2017 = Final2017.sum(axis =0)
#print(sum2017)

volume2017a = (Final2017[-1]).sum(axis =0)
volume2017b = sum2017[-1]
#print(volume2016)
print(volume2017a)
print(volume2017b)

16481053.547654
6784541800.0


In [150]:
print(type(data2016))

<class 'numpy.ndarray'>


In [186]:
diffYears = sum2017 - sum2016
#print(diffYears)

diffYearsa = volume2017a - volume2016a
print(diffYearsa)

diffYearsb = volume2017b - volume2016b
print(diffYearsb)

-4425428.559784003
-2850453900.0


In [204]:
#data2016.astype(float)

#Subtract the respective columns of both NumPy arrays and store the results into a new array called change
change = (Final2017-Final2016).astype(float)
vol1 = Final2016[:,-1]
vol2 = Final2017[:,-1]

sumVol1 = vol1.sum(axis =0)
#print(sumVol1)

sumVol2 = vol2.sum(axis =0)
#print(sumVol2)

sumChange = (sumVol2-sumVol1).sum(axis=0)

#change2 = (vol1-vol2).astype(float)
sumChange2 = change.sum(axis =0)

print(sumChange2[-1])
print(sumChange)




#Then sum up the columns of this array
#sumChange = change.sum(axis =1)
#print(sumChange)
#print(np.shape(sumChange))

-2850453900.0
-2850453900.0


In [208]:
# Verify the result - it should be the same as the difference you calculated in the previous step

#print(np.array_equal(diffYears,sumChange))

#print(np.array_equal(diffYears,sumChange))

print(np.array_equal(diffYearsa,sumChange))
print(np.array_equal(diffYearsb,sumChange))


#I will have to go through this again to clean it up

#np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
#np.set_printoptions()


False
True


In [221]:
#np.concatenate(a, b)
#print(np.shape(Final2016))
#print(np.shape(Final2017))
combined_years= np.concatenate((Final2016, Final2017))

###### Question 5
Save the new array `combined_years` to a text file, using `%10.2f` to format the prices and a comma (,) as a separator between columns.


In [223]:

np.savetxt('Total AAPL.csv', combined_years, fmt = '%10.2f', delimiter=',')

## Numpy Array Indexing and Slicing

In [235]:
import numpy as np
import csv

with open('AAPL-2017.csv',newline='') as f:
    reader = csv.DictReader(f)
    data2017 = np.empty((0,6))
    withDate2017 = np.empty((0,7))
    #print(np.shape(data2017))
    #print(np.ndim(data2017))
    for row in reader:
        oneRow = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
        data2017 = np.append(data2017,oneRow,axis=0)
        row2 = np.array([[row['Date'],row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
        withDate2017 = np.append(withDate2017,row2,axis=0)
        
print(withDate2017)

[['2017-01-03' '115.800003' '116.330002' ... '116.150002' '113.013916'
  '28781900']
 ['2017-01-04' '115.849998' '116.510002' ... '116.019997' '112.887413'
  '21118100']
 ['2017-01-05' '115.919998' '116.860001' ... '116.610001' '113.461502'
  '22193600']
 ...
 ['2017-12-27' '170.100006' '170.779999' ... '170.600006' '168.663101'
  '21498200']
 ['2017-12-28' '171.000000' '171.850006' ... '171.080002' '169.137650'
  '16480200']
 ['2017-12-29' '170.520004' '170.589996' ... '169.229996' '167.308640'
  '25884400']]


In [234]:
with open('AAPL-2016.csv',newline='') as f:
    reader = csv.DictReader(f)
    data2016 = np.empty((0,6))
    withDate2016 = np.empty((0,7))
    #print(np.shape(data2016))
    #print(np.ndim(data2016))
    for row in reader:
        oneRow = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
        data2016 = np.append(data2016,oneRow,axis=0)
        row2 = np.array([[row['Date'],row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
        withDate2016 = np.append(withDate2016,row2,axis=0)
        
print(withDate2016)
    

[['2016-01-04' '102.610001' '105.370003' ... '105.349998' '100.274513'
  '67649400']
 ['2016-01-05' '105.750000' '105.849998' ... '102.709999' '97.761681'
  '55791000']
 ['2016-01-06' '100.559998' '102.370003' ... '100.699997' '95.848511'
  '68457400']
 ...
 ['2016-12-23' '115.589996' '116.519997' ... '116.519997' '113.373917'
  '14249500']
 ['2016-12-27' '116.519997' '117.800003' ... '117.260002' '114.093948'
  '18296900']
 ['2016-12-28' '117.519997' '118.019997' ... '116.760002' '113.607445'
  '20905900']]


###### Question 1
Retrieve the rows for the month of January as a slice; you can assume that the first 20 rows is for the month of January and call the slice `january.`



In [237]:
January= withDate2016[:20]
print(January)

[['2016-01-04' '102.610001' '105.370003' '102.000000' '105.349998'
  '100.274513' '67649400']
 ['2016-01-05' '105.750000' '105.849998' '102.410004' '102.709999'
  '97.761681' '55791000']
 ['2016-01-06' '100.559998' '102.370003' '99.870003' '100.699997'
  '95.848511' '68457400']
 ['2016-01-07' '98.680000' '100.129997' '96.430000' '96.449997'
  '91.803276' '81094400']
 ['2016-01-08' '98.550003' '99.110001' '96.760002' '96.959999'
  '92.288696' '70798000']
 ['2016-01-11' '98.970001' '99.059998' '97.339996' '98.529999'
  '93.783073' '49739400']
 ['2016-01-12' '100.550003' '100.690002' '98.839996' '99.959999'
  '95.144165' '49154200']
 ['2016-01-13' '100.320000' '101.190002' '97.300003' '97.389999'
  '92.697990' '62439600']
 ['2016-01-14' '97.959999' '100.480003' '95.739998' '99.519997'
  '94.725372' '63170100']
 ['2016-01-15' '96.199997' '97.709999' '95.360001' '97.129997'
  '92.450516' '79010000']
 ['2016-01-19' '98.410004' '98.650002' '95.500000' '96.660004'
  '92.003166' '53087700']
 ['

###### Question 2

We have a slice, so let's now do the dice. Update the volume for the first row of `january` to 100. 
Is the change reflected in the original array? It should because`january` is a slice, meaning it is a view of the original array. 
Any changes made to the slice will affect the original array.

In [246]:
np.shape(January)
print(January[1][-1])
January[1][-1] = 100
print(January[1])

print(withDate2016)

#it really changed it

100
['2016-01-05' '105.750000' '105.849998' '102.410004' '102.709999'
 '97.761681' '100']
[['2016-01-04' '102.610001' '105.370003' ... '105.349998' '100.274513'
  '67649400']
 ['2016-01-05' '105.750000' '105.849998' ... '102.709999' '97.761681'
  '100']
 ['2016-01-06' '100.559998' '102.370003' ... '100.699997' '95.848511'
  '68457400']
 ...
 ['2016-12-23' '115.589996' '116.519997' ... '116.519997' '113.373917'
  '14249500']
 ['2016-12-27' '116.519997' '117.800003' ... '117.260002' '114.093948'
  '18296900']
 ['2016-12-28' '117.519997' '118.019997' ... '116.760002' '113.607445'
  '20905900']]


##### Question 3

Print the first 5 rows of the original array (do not print the `january` slice). Remember to use `set_printoptions()`introduced in the previous exercise to make your output easier to read. Verify that our earlier change to the `january` slice has affected the original array - the volume for the first row should be 100

In [254]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
#np.set_printoptions()
print(withDate2016[1:5,:])

[['2016-01-05' '105.750000' '105.849998' '102.410004' '102.709999'
  '97.761681' '100']
 ['2016-01-06' '100.559998' '102.370003' '99.870003' '100.699997'
  '95.848511' '68457400']
 ['2016-01-07' '98.680000' '100.129997' '96.430000' '96.449997'
  '91.803276' '81094400']
 ['2016-01-08' '98.550003' '99.110001' '96.760002' '96.959999'
  '92.288696' '70798000']]


##### Question 4
Now we want to find the highest closing price for the year

In [293]:
#([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
theClose = (data2017[:,3]).astype(float)
maxClose= (theClose).max()
print(maxClose)

176.419998


##### Question 5

Finally, vertically slice the High and Low price columns and display just their first 5 rows.


In [283]:
theOpen = data2017[:,0]
theHigh = data2017[:,1]
theLow = data2017[:,2]

#print(theOpen[:5])
print(theHigh[:5])
print(theLow[:5])
print("")
print(data2017[:5,:3])

['116.330002' '116.510002' '116.860001' '118.160004' '119.430000']
['114.760002' '115.750000' '115.809998' '116.470001' '117.940002']

[['115.800003' '116.330002' '114.760002']
 ['115.849998' '116.510002' '115.750000']
 ['115.919998' '116.860001' '115.809998']
 ['116.779999' '118.160004' '116.470001']
 ['117.949997' '119.430000' '117.940002']]


## Broadcasting

In [298]:
newOpen = theOpen.astype(float) * 1.1
newClose = theClose.astype(float) * 1.2

print(newOpen[:5])
print(theOpen[:5])
print(newClose[:5])
print(theClose[:5])


theOpen = data2017[:,0]
theHigh = data2017[:,1]
theLow = data2017[:,2]

[127.3800033 127.4349978 127.5119978 128.4579989 129.7449967]
['115.800003' '115.849998' '115.919998' '116.779999' '117.949997']
[139.3800024 139.2239964 139.9320012 141.4920048 142.7879976]
[116.150002 116.019997 116.610001 117.910004 118.989998]
